# rubocop.yml - settings for Rubocop Ruby static code analyzer
Metrics/LineLength:
  Max: 85
  Exclude:
    - 'test/**/*'
    - 'minitest-reporters-json_reporter.gemspec'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
Style/Semicolon:
  Exclude:
    - 'test/**/*'
#    - 'lib/minitest/reporters/json_reporter.rb'

Metrics/ClassLength:
  Max: 140

Style/GlobalVars:
  Exclude:
    - 'test/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/fake_tests.rb'